package com.luc.qa.module.alumni.entity;

public enum Faculty {
    LITERATURE_AND_HUMAN_SCIENCES,
    INFORMATION_AND_DOCUMENTATION,
    LAW_POLITICAL_AND_ADMINISTRATIVE_SCIENCES,
    ECONOMIC_SCIENCES_AND_BUSINESS_ADMINISTRATION,
    SCIENCES,
    EDUCATION,
    ENGINEERING,
    AGRICULTURE_AND_VETERINARY_SCIENCES,
    MEDICAL_SCIENCES,
    DENTISTRY,
    PHARMACY,
    PUBLIC_HEALTH,
    FINE_ARTS_AND_ARCHITECTURE,
    TOURISM_AND_HOSPITALITY_MANAGEMENT,
    SOCIAL_SCIENCES,
    TECHNOLOGY,
    INSTITUTE_OF_PHYSICAL_EDUCATION
}
